#!/bin/sh
### BEGIN INIT INFO
# Provides:          myservice
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start myservice at boot time
# Description:       Enable service provided by daemon myservice.
### END INIT INFO

PATH="/bin:/usr/bin:/sbin:/usr/sbin"
DESC="kclient service"
NAME="kclient"
DAEMON="/usr/bin/node"
DAEMONOPTS="/usr/local/lib/kclient/index.js"
PIDFILE="/var/run/kclient.pid"
SCRIPTNAME="/etc/init.d/$NAME"

# Function to find the initiating user
get_initiating_user() {
  local current_pid=$$
  local found_user=""

  while [ "$current_pid" -ne 1 ] && [ "$current_pid" -ne 0 ]; do
    local ps_output
    ps_output=$(ps -o user=,ppid= -p "$current_pid" 2>/dev/null)
    
    if [ -z "$ps_output" ]; then
      break
    fi
    
    local user ppid
    user=$(echo "$ps_output" | awk '{print $1}')
    ppid=$(echo "$ps_output" | awk '{print $2}')
    
    if [ "$user" != "root" ] && [ -n "$user" ]; then
      found_user="$user"
      break
    fi
    
    current_pid=$ppid
  done
  
  if [ -n "$found_user" ]; then
    echo "$found_user"
  else
    echo "root"
  fi
}

EXEUSER=$(get_initiating_user)

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting service" "$NAME"
        start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $EXEUSER --chuid $EXEUSER --exec $DAEMON -- $DAEMONOPTS
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping service" "$NAME"
        start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
        pkill -xf "$DAEMON $DAEMONOPTS" || true
        RETVAL="$?"
        log_end_msg $RETVAL
        rm -f "$PIDFILE"
        if [ $RETVAL != 0 ]; then
            exit 1
        fi
        rm -f "$PIDFILE"
        ;;
    restart)
        log_daemon_msg "Restarting service" "$NAME"
        $0 stop
        $0 start
        ;;
    status)
        status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac
exit 0